name: Run Cypress Tests

on:
    push:
        branches:
            - main
    workflow_dispatch:
        inputs:
            update-snapshots:
                description: "Update snapshots"
                required: true
                type: choice
                options:
                    - "false"
                    - "true"
                default: "false"
env:
    UPDATE_SNAPSHOTS: ${{ github.event.inputs.update-snapshots || 'false' }}

jobs:
    cypress-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install dependencies
              run: npm install ts-node typescript

            - name: Run Cypress tests in Docker
              run:
                  docker run -v ${{ github.workspace }}:/e2e -w /e2e cypress/included:13.3.3 \
                  npx ts-node cypress run --env GHA=true,updateSnapshots=${{ env.UPDATE_SNAPSHOTS }}

            - name: Store Test Results
              if: always()
              run: |
                  mkdir -p results
                  if [ -d "cypress/screenshots" ]; then cp -r cypress/screenshots results/screenshots; fi

            - name: Store Snapshots
              if: always()
              run: |
                  mkdir -p results/snapshots
                  if [ -d "cypress/snapshots" ]; then cp -r cypress/snapshots/* results/snapshots; fi

            - name: Archive artifacts
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: artifacts
                  path: results
                  retention-days: 10
