name: Run Cypress Tests

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    cypress-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install dependencies
              run: npm install ts-node typescript

            - name: Run Cypress tests in Docker
              run: docker run -v ${{ github.workspace }}:/e2e -w /e2e cypress/included:13.3.3 npx ts-node cypress run
